services:
  - type: web
    name: alibi-server
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
